### PR TITLE
[RFC] Overhaul highlighting, and more

### PR DESCRIPTION
**Pull request by atweiden**
Syntax changes, from left-field.

From most agreeable to least agreeable.

- [vimscript] Change how syntax keywords are defined
- [syntax] Highlight string delimiters differently from string contents
- [syntax] Rethink

### CODE REVIEW

**Comment by andrewrk** [comment]
Hello - I'm down to try some new thing. One thing from the screenshot, I think `try` and `return` should be the same color because those are both control flow that affect the return value.

**Comment by atweiden** [comment]
Ok. Consider it ready to `try`.

**Comment by atweiden** [comment]
This variant has grown on me. In [another branch](https://github.com/atweiden/vim-zig/tree/tttc), I switched #36's string delims to `Delimiter` highlighting and brought back `try` as `Keyword`. Third time's the charm?

**Comment by haze** [comment]
You mentioned that you wanted to proceed with #37, so I will close this issue. Feel free to reopen

**Pull request closed without merging**
