### PR TITLE
[RFC] Overhaul highlighting — flipped

### PR DESCRIPTION
**Pull request by atweiden**
An iteration on #36. It's probably what I'll be using on my personal fork.

### CODE REVIEW

**Comment by andrewrk** [comment]
wait so which one did you want merged?

**Comment by atweiden** [comment]
My preference is for #37.

I would value reading your feedback after having used either theme variant to develop Zig over the course of several days. I have only tested them with [seoul256](https://github.com/junegunn/seoul256.vim).

Also, I can squash the commits down if you'd like.

**Comment by atweiden** [comment]
New variant of this one.





My general thought is variable declarations happen frequently in Zig, and if those aren't a neutral color, viewing zig files gets too intense. I like putting language-specific idioms in green, because it reminds me of alien technology. So that is why I put built-in functions in green. I don't love highlighting `try` and `error` in splotchy red, but I keep coming back to the semantic value of knowing where errors might be at a lazy glance more than offsetting the cost of the splotchy red and perhaps logical inconsistency. I wouldn't mind making it a configuration setting.

Available at https://github.com/atweiden/vim-zig/tree/tttc

**Comment by haze** [comment]
Hi @atweiden! I just want to start by saying thanks for investing time into the vim plugin!

I really like the changes you've made so far, but I was wondering if we could take it a step further to provide maximal theming capabilities to colorscheme creators. I feel like the discussion you had with Andrew about what to highlight `try`/`return` as is a good example of a problem that shouldn't matter because the plugin should provide the facilities to choose.

I want to move forward with this PR, but I am wondering if it is also possible to provide regions for highlight groups (like the already defined `zigStatement` group) **and** keywords, in case colorscheme authors want to prioritize/independently highlight based on their own criteria (instead of solely relying on the plugin for the consensus on those groups)

There are also a couple of other miscellaneous things that mind as well get grouped in with a huge refactor **if it's not too much to ask for**, such as:
1. line 211, the `zigType` regex doesn't support `u0` or `i0`. I don't think this popped up because it's explicitly a `zigType` in the `zig_syntax_keywords` list
2. is there a way to provide different syntax regions for different kinds of groups? I think `blk: {` and family are okay with being `zigBlock`, but it would be cool if we could selectively highlight different elements under different areas (e.g member doc comments vs top level struct comments). I tried doing this already by modifying line 226 and copying the `struct {` and `union(enum) {` start regions, but I'm not 100% sure how that works so I moved on.

Also, I see that you removed the TODO for `match only the first '\\' within the zigMultilineString as zigMultilineStringPrefix`, was this fixed?

**Comment by atweiden** [comment]
> Hi @atweiden! I just want to start by saying thanks for investing time into the vim plugin!

You're quite welcome. I thought I'd share what I had in case there were other Vim users who'd find it valuable. I'm glad to see there are.

I consider the [tttc branch](https://github.com/ziglang/zig.vim/pull/37#issuecomment-743979689) effectively the successor to this branch at this point. But this is an RFC because it's open to interpretation.

> I am wondering if it is also possible to provide regions for highlight groups (like the already defined zigStatement group) and keywords, in case colorscheme authors want to prioritize/independently highlight based on their own criteria (instead of solely relying on the plugin for the consensus on those groups)

Yes, it's possible for authors of color scheme plugins to override the highlighting groups defined by zig.vim, e.g.

```vim
highlight clear zigMacro
highlight zigMacro ctermbg=...
```

This way, they can opt to add special handling for Zig.

With what granularity do you propose zig.vim's highlighting groups should be defined? e.g. `null` is in the `zigBoolean` group out of expediency, not correctness. It could be moved into a `zigNull` group for instance. And I can make further changes in this direction. Admittedly I hadn't put much thought into it, as this PR is first and foremost about aesthetics.

> line 211, the zigType regex doesn't support u0 or i0. I don't think this popped up because it's explicitly a zigType in the zig_syntax_keywords list

Correct, I inherited that from the existing codebase. Both `u0` and `i0` are highlighted as a `zigType` as is. Is there a benefit to overhauling the Vim regex, rather than defining them separately?

> is there a way to provide different syntax regions for different kinds of groups? I think blk: { and family are okay with being zigBlock, but it would be cool if we could selectively highlight different elements under different areas (e.g member doc comments vs top level struct comments). I tried doing this already by modifying line 226 and copying the struct { and union(enum) { start regions, but I'm not 100% sure how that works so I moved on.

All of that is possible, of course, and it's something I've thought about, particularly in relation to `const` and `var`. I briefly considered dabbling with highlighting `blk:` as `Identifier`, as well. However, it's a lot of work. And considering the imminent rise of tree-sitter in at least Neovim I'm reluctant to spend significant time getting fancy with Vim regexes. My mind can be changed on this, but I would prefer to consider this out of scope for this PR.

> Also, I see that you removed the TODO for match only the first '\\' within the zigMultilineString as zigMultilineStringPrefix, was this fixed?

Yes, it's fixed now.

**Comment by haze** [comment]
> With what granularity do you propose zig.vim's highlighting groups should be defined? e.g. null is in the zigBoolean group out of expediency, not correctness. It could be moved into a zigNull group for instance. And I can make further changes in this direction. Admittedly I hadn't put much thought into it, as this PR is first and foremost about aesthetics.

I now think at this point the groups you have defined in the `tttc` branch are sufficient.

> All of that is possible, of course, and it's something I've thought about, particularly in relation to const and var. I briefly considered dabbling with highlighting blk: as Identifier, as well. However, it's a lot of work. And considering the imminent rise of tree-sitter in at least Neovim I'm reluctant to spend significant time getting fancy with Vim regexes. My mind can be changed on this, but I would prefer to consider this out of scope for this PR.

I'm actually keen on keeping support for native vim clients, but you're right in your thinking that the more elaborate parsing should be reserved for the capable tools--it is out of scope for this PR.

I am okay with moving forward on merging what you have in your `tttc` branch, if possible, could you open another PR with that branch?

**Comment by atweiden** [comment]
Will do.

**Pull request closed without merging**
